version: "3"

services:

  mongo:
    container_name: ghost-network-mongo
    image: mongo:5.0.8
    ports:
      - "27017:27017"

  rabbit:
    container_name: ghost-network-rabbit
    image: rabbitmq:3.9.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=sDAM4xyhwCpDAEXy8r4v
