name: Release stable version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  push-image:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/ghosts-network/news-feed:$(echo "${{ github.ref_name }}" | sed 's/v//g')
            --tag ghcr.io/ghosts-network/news-feed:latest .
